version: '3'

services:
  database:
    container_name: db
    build: docker/database
    ports:
      - "5432:5432"
    volumes:
      - ./docker/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES-DATABASE=postgres

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/var/www/app
      - ./docker/app/log:/var/log/flask
    depends_on:
      - database
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - TEMPLATES_AUTO_RELOAD=1
    command: flask run --host=0.0.0.0 --port=5000
